#!/usr/bin/env bash
# Run ANY scenario in WSL Ubuntu: sim/scenarios/<name>.json -> CM1 -> netCDF.
#
# The generic replacement for sim/single_cell/run.sh, which hardcoded its run dir,
# rank count, grid line and provenance strings (docs/phase2-plan-2026-07-20.md 10.6).
# Everything that used to be a hardcoded echo is now READ FROM THE SCENARIO CONFIG,
# so run_meta.txt cannot describe a different run than the one that executed.
#
# The deck is GENERATED, never copied: pipeline/gen_deck.py renders the scenario over
# sim/templates/base.namelist.input. That is what makes "same JSON simulates and
# exports" true rather than aspirational -- the export geometry and the sim geometry
# are read from one file.
#
# Output (netCDF) goes to WSL ext4 under the config's run_dir -- NEVER through /mnt/*
# (charter data policy: the 9P bridge is slow, raw output is large and disposable).
#
# Usage (from Windows):
#   wsl -d Ubuntu -- bash /mnt/m/claud_projects/thunderstorm/sim/run_scenario.sh single_cell_333m
# Usage (inside WSL):
#   bash run_scenario.sh single_cell_333m [--dry-run]
set -euo pipefail

SCENARIO="${1:-}"
DRY_RUN=0
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=1

if [[ -z "$SCENARIO" ]]; then
  echo "usage: run_scenario.sh <scenario-name> [--dry-run]" >&2
  echo "available:" >&2
  ls "$(dirname "${BASH_SOURCE[0]}")/scenarios"/*.json 2>/dev/null \
    | xargs -n1 basename | sed 's/\.json$/  /;s/^/  /' >&2
  exit 2
fi

SELFDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SELFDIR/.." && pwd)"
CONFIG="$SELFDIR/scenarios/$SCENARIO.json"
CM1_EXE="/home/boiko/thunderstorm/runs/cm1.exe"   # validated cm1r21.1 (docs/phase0-cm1-build.md)
NRANKS=8                                           # locked by the Phase 0 benchmark gate

[[ -f "$CONFIG"   ]] || { echo "ERROR: no scenario config at $CONFIG" >&2; exit 1; }
[[ -x "$CM1_EXE"  ]] || { echo "ERROR: cm1.exe not found at $CM1_EXE" >&2; exit 1; }

# Pull run_dir and the provenance block out of the JSON with the same loader the
# pipeline uses -- not with grep, so the config cannot be read two different ways.
read_cfg() { python3 "$REPO/pipeline/scenario_info.py" --scenario "$SCENARIO" "$@"; }

RUNDIR="$(read_cfg --run-dir)"
[[ "$RUNDIR" == /mnt/* ]] && {
  echo "ERROR: run_dir $RUNDIR is on the Windows 9P bridge. Raw CM1 output must" >&2
  echo "       stay on WSL ext4 (charter data policy)." >&2; exit 1; }

# Generate the deck BEFORE touching the run dir: gen_deck.py refuses a scenario whose
# output flags would make the run unexportable, and catching that here costs seconds
# instead of hours.
DECK="$(mktemp)"
trap 'rm -f "$DECK"' EXIT
echo "=== generating deck from $CONFIG ==="
python3 "$REPO/pipeline/gen_deck.py" --scenario "$SCENARIO" -o "$DECK"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "=== --dry-run: deck generated and validated, not running CM1 ==="
  exit 0
fi

mkdir -p "$RUNDIR"
cp "$CM1_EXE" "$RUNDIR/cm1.exe"
cp "$DECK" "$RUNDIR/namelist.input"
cp "$CONFIG" "$RUNDIR/scenario.json"   # the config that produced this run, beside it
cd "$RUNDIR"

# Reproducibility provenance (charter Conventions: binary hash, rank count, grid,
# decomposition). Every scenario-specific line comes from the JSON.
{
  echo "scenario         : $SCENARIO"
  echo "scenario_config  : sim/scenarios/$SCENARIO.json"
  echo "cm1_binary_sha256: $(sha256sum cm1.exe | awk '{print $1}')"
  echo "nranks           : $NRANKS"
  echo "grid             : $(read_cfg --grid-line)"
  read_cfg --provenance
  echo "openmpi          : $(mpirun --version 2>/dev/null | head -1)"
  echo "deck             : GENERATED by pipeline/gen_deck.py (see namelist.input here)"
} | tee run_meta.txt

rm -f cm1out*.nc cm1out.nc

echo "=== launching CM1: mpirun -np $NRANKS ./cm1.exe ==="
time mpirun -np "$NRANKS" ./cm1.exe > cm1.out 2>&1
echo "=== CM1 finished; tail of cm1.out ==="
tail -n 20 cm1.out
echo "=== output files ==="
ls -lh cm1out*.nc 2>/dev/null | tail -5 || ls -lh *.nc 2>/dev/null | tail -5
echo "SCENARIO_DONE $SCENARIO"
