#!/usr/bin/env bash
# Phase 3 T5 -- run ONE 1 km probe. Throwaway; not a shipped scenario.
#
# sim/run_scenario.sh takes a scenario NAME out of sim/scenarios/ and is locked to
# np=8. Probe configs are NOT shippable scenarios and must not land in
# sim/scenarios/ (nothing there may be unexportable), and the probes run
# two-at-a-time at 4 ranks each per the charter's concurrency note. So this is a
# probe-local runner over sim/probes/configs/ -- but it still generates the deck
# with the PRODUCTION generator (pipeline/gen_deck.py), which is what makes the
# probe decks comparable to the shipped ones, and it still records the binary
# sha256 (T4: runs/cm1.exe is a SYMLINK into the build tree, so the pin cannot be
# assumed).
#
#   bash sim/probes/run_probe.sh sim/probes/configs/t5probe_c2.json 4
set -euo pipefail

CONFIG="$1"
NRANKS="${2:-4}"
REPO=/mnt/m/claud_projects/thunderstorm
CM1_EXE=/home/boiko/thunderstorm/runs/cm1.exe

NAME="$(basename "$CONFIG" .json)"
RUNDIR="/home/boiko/thunderstorm/runs/$NAME"

echo "=== $NAME: generating deck from $CONFIG ==="
DECK="$(mktemp)"
SND="$(mktemp)"; SND_REPORT="$(mktemp)"
trap 'rm -f "$DECK" "$SND" "$SND_REPORT"' EXIT
python3 "$REPO/pipeline/gen_deck.py" --scenario "$CONFIG" -o "$DECK"

# The external sounding (isnd=7 probes -- T5s) is CM1's SECOND scenario input, and
# this script used to know nothing about it: an isnd=7 probe would have run against
# whatever input_sounding happened to be in the run dir. Deck generation has already
# refused any isnd/sounding-block mismatch (deck.py Category 6) by the time we get
# here, so this only has to render the file the config declares.
HAS_SOUNDING="$(python3 "$REPO/pipeline/scenario_info.py" --scenario "$CONFIG" --has-sounding)"
if [[ "$HAS_SOUNDING" == "1" ]]; then
  echo "=== $NAME: generating input_sounding from $CONFIG ==="
  python3 "$REPO/pipeline/gen_sounding.py" --scenario "$CONFIG" -o "$SND" --report "$SND_REPORT"
fi

# The pre-registration document is the config's own, not a constant: T5 probes point
# at the T5 doc, T5s probes at the 2026-09-02 plan. A run_meta.txt naming the wrong
# document is a provenance defect of exactly the kind this file exists to prevent.
PREREG="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['sim']['provenance'].get('probe_of','docs/phase3-t5-multicell.md'))" "$CONFIG")"

mkdir -p "$RUNDIR"
cp "$CM1_EXE" "$RUNDIR/cm1.exe"
cp "$DECK" "$RUNDIR/namelist.input"
cp "$CONFIG" "$RUNDIR/scenario.json"
# Probe run dirs are per-name and PERSISTENT, so a stale input_sounding from an
# earlier version of this config is the real hazard: a missing file is fail-fast
# (base.F err=9009), a stale one is read silently. Remove first, then stage.
rm -f "$RUNDIR/input_sounding" "$RUNDIR/input_sounding.report.json"
if [[ "$HAS_SOUNDING" == "1" ]]; then
  cp "$SND" "$RUNDIR/input_sounding"
  cp "$SND_REPORT" "$RUNDIR/input_sounding.report.json"
fi
cd "$RUNDIR"

{
  echo "probe            : $NAME"
  echo "cm1_binary_sha256: $(sha256sum cm1.exe | awk '{print $1}')"
  if [[ "$HAS_SOUNDING" == "1" ]]; then
    echo "input_sounding_sha256: $(sha256sum input_sounding | awk '{print $1}')"
    echo "sounding         : EXTERNAL, GENERATED by pipeline/gen_sounding.py (isnd=7)"
  else
    echo "sounding         : analytic (CM1 isnd option in namelist.input, no input_sounding)"
  fi
  echo "nranks           : $NRANKS"
  echo "config           : $CONFIG"
  echo "pre-registration : $PREREG"
} | tee run_meta.txt

rm -f cm1out*.nc cm1out.nc
echo "=== $NAME: mpirun -np $NRANKS ./cm1.exe ==="
if time mpirun -np "$NRANKS" ./cm1.exe > cm1.out 2>&1; then
  echo "PROBE_OK $NAME" | tee "$RUNDIR/PROBE_STATUS"
else
  echo "PROBE_FAIL $NAME (exit $?)" | tee "$RUNDIR/PROBE_STATUS"
  tail -n 30 cm1.out
  exit 1
fi
ls cm1out*.nc | wc -l
