#!/usr/bin/env bash
# Phase 3 T7 -- the fork-neutrality generality gate.
#
# docs/phase3-t4-seed.md 4.1 left ONE claim as an extrapolation rather than a
# measurement: "the fork is bitwise-neutral for every irandp=0 run at any grid and
# rank count", measured at exactly one configuration (500 m, 60x60, np=4). The
# charter's recovery path -- "regeneration from sim/ + pipeline/" -- runs the FORKED
# binary and every shipped scenario declares irandp=0, so that extrapolation is what
# stands between a lost package and a recoverable one.
#
# This gate settles it at a SECOND configuration that differs in BOTH quantities the
# extrapolation was scoped on: single_cell_500m at 160x160x40, np=8.
#
# Pre-registration (claim, comparisons, branches, what it does NOT settle):
#   docs/phase3-completion-2026-09-06.md 2
#
# Design, in one line each:
#   - ONE deck, generated by the PRODUCTION generator, copied to both members, so no
#     difference between them can come from their input;
#   - both members run TODAY, so comparison 1 is immune to machine drift since July;
#   - the July run's own output is the baseline, and this script must never be able to
#     write into the directory holding it (see REFUSAL 3).
#
#   bash sim/gates/t7_neutrality.sh
set -euo pipefail

REPO=/mnt/m/claud_projects/thunderstorm
BASE=/home/boiko/thunderstorm/runs
SCENARIO=single_cell_500m
NRANKS=8

BASELINE="$BASE/singlecell"                 # the July stock run -- READ ONLY, never written
FORK_EXE="$BASE/cm1.exe"                    # symlink into the build tree (T4)
STOCK_EXE="$BASELINE/cm1.exe"               # the copy the July run kept beside itself
FORK_SHA=5fc9301623fb2f8b00ebf476cef39b7046e50a2ce0bacfdad560941ae80eb59d
STOCK_SHA=5da2c2aa49b9f226cedb5c833219d915dca71c4f328923e47cdbf596bab016bd

FORK_DIR="$BASE/t7neutral_fork"
STOCK_DIR="$BASE/t7neutral_stock"

say() { echo "[t7-neutrality] $*"; }
die() { echo "[t7-neutrality] REFUSED: $*" >&2; exit 1; }

# ---------------------------------------------------------------- exclusive lock
# Same lesson as sim/probes/run_probe.sh: two invocations sharing a run dir silently
# truncate each other's inputs and interleave one log. fd 9 is released on any exit.
LOCK="$BASE/.t7neutral.lock"
exec 9>"$LOCK"
flock -n 9 || die "another t7_neutrality.sh holds $LOCK. Wait, or kill it BY PID."

# ------------------------------------------------------- REFUSAL 1: two binaries
# If both members ran the same binary the gate would PASS trivially and say nothing.
# The hashes are asserted against the values docs/ and run_meta.txt record, so a
# rebuild that quietly changed either one stops the gate instead of being averaged in.
[[ -x "$FORK_EXE"  ]] || die "no fork binary at $FORK_EXE"
[[ -x "$STOCK_EXE" ]] || die "no stock binary at $STOCK_EXE"
got_fork=$(sha256sum "$FORK_EXE"  | awk '{print $1}')
got_stock=$(sha256sum "$STOCK_EXE" | awk '{print $1}')
[[ "$got_fork"  == "$FORK_SHA"  ]] || die "fork binary is $got_fork, expected $FORK_SHA"
[[ "$got_stock" == "$STOCK_SHA" ]] || die "stock binary is $got_stock, expected $STOCK_SHA"
[[ "$got_fork" != "$got_stock"  ]] || die "both members would run the SAME binary"
say "binaries verified: fork ${got_fork:0:16} != stock ${got_stock:0:16}"

# ------------------------------------------------ REFUSAL 2: the baseline exists
n_base=$(ls "$BASELINE"/cm1out_*.nc 2>/dev/null | wc -l)
[[ "$n_base" -gt 0 ]] || die "no baseline output in $BASELINE -- nothing to compare against"
say "baseline: $n_base cm1out_*.nc in $BASELINE"

# ------------------------------- REFUSAL 3: never write into a scenario's run_dir
# sim/run_scenario.sh runs into the config's OWN run_dir and rm -f's cm1out*.nc first.
# For single_cell_500m that directory IS the baseline. This gate writes only into dirs
# that no scenario claims -- checked against every config, not just this one.
for cfg in "$REPO"/sim/scenarios/*.json; do
  name=$(basename "$cfg" .json)
  rd=$(python3 "$REPO/pipeline/scenario_info.py" --scenario "$name" --run-dir)
  for target in "$FORK_DIR" "$STOCK_DIR"; do
    [[ "$(readlink -m "$target")" == "$(readlink -m "$rd")" ]] \
      && die "$target is the run_dir of scenario $name -- refusing to overwrite it"
  done
done
say "run dirs are free of every scenario run_dir"

# ------------------------------------------------------------ ONE generated deck
# The PRODUCTION generator, and then --verify against the July run's own namelist.
# Without this a byte difference downstream could mean "the fork differs" OR "we ran a
# different deck", and the gate would prove nothing.
DECK=$(mktemp)
trap 'rm -f "$DECK"' EXIT
say "generating deck for $SCENARIO"
python3 "$REPO/pipeline/gen_deck.py" --scenario "$SCENARIO" -o "$DECK" >/dev/null
python3 "$REPO/pipeline/gen_deck.py" --scenario "$SCENARIO" \
        --verify "$BASELINE/namelist.input" | tail -3
say "deck verified against the baseline run's own namelist.input"

# ----------------------------------------------------------------- the two runs
run_member() {
  local dir="$1" exe="$2" label="$3"
  say "=== member $label -> $dir"
  rm -rf "$dir"; mkdir -p "$dir"
  cp "$DECK" "$dir/namelist.input"
  cp "$exe"  "$dir/cm1.exe"
  cd "$dir"
  {
    echo "gate             : phase3 T7 fork-neutrality generality"
    echo "preregistration  : docs/phase3-completion-2026-09-06.md 2"
    echo "member           : $label"
    echo "scenario         : $SCENARIO (deck generated by pipeline/gen_deck.py)"
    echo "cm1_binary_sha256: $(sha256sum cm1.exe | awk '{print $1}')"
    echo "namelist_sha256  : $(sha256sum namelist.input | awk '{print $1}')"
    echo "nranks           : $NRANKS"
    echo "baseline         : $BASELINE"
    echo "openmpi          : $(mpirun --version 2>/dev/null | head -1)"
    echo "started          : $(date -Is)"
  } | tee run_meta.txt
  say "launching mpirun -np $NRANKS ./cm1.exe"
  time mpirun -np "$NRANKS" ./cm1.exe > cm1.out 2>&1
  # Sorted by FILENAME so the two members' lists are directly diffable.
  sha256sum cm1out_*.nc | sort -k2 > SHA256SUMS
  say "member $label done: $(wc -l < SHA256SUMS) output files hashed"
}

run_member "$FORK_DIR"  "$FORK_EXE"  fork
run_member "$STOCK_DIR" "$STOCK_EXE" stock

# The baseline's hashes are computed the same way, with the same sort, from the
# July files -- which are never modified, only read.
( cd "$BASELINE" && sha256sum cm1out_*.nc | sort -k2 ) > "$BASE/t7neutral_baseline.SHA256SUMS"

# --------------------------------------------------------- the three comparisons
compare() {
  local a="$1" b="$2" label="$3"
  local na nb ndiff
  na=$(wc -l < "$a"); nb=$(wc -l < "$b")
  if [[ "$na" != "$nb" ]]; then
    echo "COMPARISON $label : FAIL (file COUNT differs: $na vs $nb)"
    return
  fi
  ndiff=$(diff <(cat "$a") <(cat "$b") | grep -c '^<' || true)
  if [[ "$ndiff" == "0" ]]; then
    echo "COMPARISON $label : IDENTICAL ($na files)"
  else
    echo "COMPARISON $label : DIFFERENT ($ndiff of $na files differ)"
    diff <(cat "$a") <(cat "$b") | grep '^<' | head -5
  fi
}

echo
echo "================ T7 fork-neutrality gate -- results ================"
compare "$FORK_DIR/SHA256SUMS"  "$STOCK_DIR/SHA256SUMS"            "1 A(fork) vs B(stock), both today"
compare "$STOCK_DIR/SHA256SUMS" "$BASE/t7neutral_baseline.SHA256SUMS" "2 B(stock) vs July on-disk"
compare "$FORK_DIR/SHA256SUMS"  "$BASE/t7neutral_baseline.SHA256SUMS" "3 A(fork)  vs July on-disk"
echo "===================================================================="
echo "T7_NEUTRALITY_DONE"
